// Spielkonstanten
export const GAME_CONFIG = {
    FIELD_WIDTH: 100,
    FIELD_DEPTH: 60,
    PLATFORM_THICKNESS: 2,
    TANK_BASE_SIZE: { width: 2.2, height: 1.0, depth: 3.5 },
    PLAYER1_TANK_COLOR: 0xF44336,
    PLAYER2_TANK_COLOR: 0xFF9800,
    SELECTED_TANK_EMISSIVE: 0xff8888,
    MAX_TANK_MOVE_DISTANCE: 100 / 4.5,
    NUM_TANKS_PER_PLAYER: 5,
    MIN_MOVE_THRESHOLD: 1e-4,
    NUM_FIR_TREES: 10,
    NUM_MOUNTAINS: 14,
    TURRET_SWEEP_SPEED: 2 * Math.PI,
    MIN_CAMERA_RADIUS: 30,
    MAX_CAMERA_RADIUS: 220
};

// Spielzustände
export const GAME_STATE = {
    INITIAL: 'INITIAL',
    SELECT_TANK: 'SELECT_TANK',
    MOVE_TANK: 'MOVE_TANK',
    TANK_MOVING: 'TANK_MOVING',
    AWAITING_END_TURN_CLICK: 'AWAITING_END_TURN_CLICK',
    GAME_OVER: 'GAME_OVER'
}; 